### ISSUE TITLE
Broken image in README

### ISSUE THREAD

**Issue by ikurochkin** [Raiffeisen-DGTL/The-Way-of-CICD-Open-Source-Edition#4]
Hi, looks like the pipeline-hld.png in the README is broken.
Link https://github.com/Raiffeisen-DGTL/The-Way-of-CICD-Open-Source-Edition/blob/main/docs-logo/pipeline-hld.png

**Comment by evgeniy-kharchenko** [comment]
Hi, thank you.
Will fix this one during next week.

**Comment by evgeniy-kharchenko** [comment]
Hi there, we've added some pipeline hld sheme via `mermaid` instead of png.
The diif can be found at the MR: https://github.com/Raiffeisen-DGTL/The-Way-of-CICD-Open-Source-Edition/pull/5
